### ISSUE TITLE
Please provide a library.json for platformio

### ISSUE THREAD

**Issue by probonopd** [mrdunk/esp8266_mdns#2]
It would be nice if a `library.json` for [platformio](http://platformio.org/) could be included.

**Comment by mrdunk** [comment]
since i have no experience with platformio it's unlikely i will be adding this.
i will happily approve the addition of a library.json if you would like to supply one though.

**Comment by mrdunk** [comment]
commit 3327a7f addresses this.
many thanks for the addition.
