### ISSUE TITLE
Please add to Arduino Library Manager

### ISSUE THREAD

**Issue by probonopd** [mrdunk/esp8266_mdns#3]
Please make this library available in the Arduino [Library Manager](https://www.arduino.cc/en/Guide/Libraries#toc3). 
- Ensure your library is complaint with [1.5 format](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification)(1.5 format folder layout is not required)
- Tag it and push the tag, or create a release with github "releases"
- Open an issue on [Arduino's github](https://github.com/arduino/Arduino/issues), specifying the git repo (or github url) from where to download your library

More information on https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by mrdunk** [comment]
in theory this is a good idea.

it won't happen soon however.
i'm not currently working on the esp8266 and have no prior Arduino experience so would need to do a little research to make it happen.

i'll happily approve commits from you if you have the spare time.
alternatively i'll look into it next time i'm working with this code.

thanks for the feedback.

**Comment by mrdunk** [comment]
commit 9713a06 addresses this.
thanks for the submission.
is there anything else we need for this or should this issue be marked 'closed'?

**Comment by probonopd** [comment]
Please create a release with github "releases". Then I can open an issue on Arduino's github repo.

**Comment by mrdunk** [comment]
https://github.com/mrdunk/esp8266_mdns/releases/tag/v1.0

**Comment by probonopd** [comment]
https://github.com/arduino/Arduino/issues/4532

**Comment by mrdunk** [comment]
acknowledged.
thanks for the help.

**Comment by probonopd** [comment]
https://github.com/arduino/Arduino/issues/4532#event-577678660
