### ISSUE TITLE
Please add solution to bind method as callback rather than functions

### ISSUE THREAD

**Issue by kelcon** [mrdunk/esp8266_mdns#6]
I have tried:

my_mdns = mdns::MDns(NULL, NULL, std::bind(&myclass::_answerCallback, this))

but this doesn't work

thank you in advance for suggestion

**Comment by mrdunk** [comment]
i don't have much experience with std::bind()...
looking at the documentation it appears you need to provide a placeholder for the argument to the callback.
also, i'm not convinced "this" will point to the correct object here.
what does the compiler say?

does something like this work?

```
    myclass myclass_instance;
    my_mdns = mdns::MDns(NULL, NULL, std::bind(&myclass::_answerCallback,myclass_instance , _1));
```

**Comment by mrdunk** [comment]
the simple (although slightly less efficient) way to do this would be to use a callback function to wrap your  method call.

```
// Initialise a global instance of your class.
myclass myclass_instance;

// Callback function.
void answerCallback(const mdns::Answer* answer){
  myclass_instance._answerCallback(answer);
}

// Initialise MDns.
mdns::MDns my_mdns(NULL, NULL, answerCallback);
```

**Comment by malachib** [comment]
Qualifier: My C++ is super rusty, but getting better.

Doing callbacks on instance methods is a bit involved and also not directly compatible with regular function pointers.  Even if mrdunk makes it work, he may break his existing function pointer approach.  I've taken to occasionally force-casting 

void (*func)(void\* context)
to
void (TClass::*func)()

but I don't really expect that to work out in the long run.

It seems like some flavor of std::bind might get you there, although it also seems in this context like it's syntactic sugar for wrapping a regular function.
